name: asistencias_movil
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  table_calendar: ^3.0.1
  flutter_launcher_icons: "^0.9.3"
  geolocator: ^10.1.0
  flutter_localizations:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/utils/
    - assets/utils/home.png